### ISSUE TITLE
Mainnet vs Simnet vs Testnet

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#188] opened 2017-04-15 09:34 UTC
The difference between these, what they should be used for. How to use them.

I think the only thing we already have on this topic is [the different type of addresses]( https://docs.decred.org/faq/wallets-and-seeds/#9-what-are-the-different-types-of-addresses)

[Here](https://gist.github.com/davecgh/2992ed85d41307e794f6) is a good resource explaining simnet for btcd, which is mostly analogous for dcrd.

Could mention testnet faucet here as well - the only place we currently mention it is in the Testnet voting guide, and I assume we will be replacing that soon in favour of a Mainnet voting guide

**Comment by jcvernaleo** [comment] 2017-04-15 15:05
I think simnet should be kept separate from mainnet vs. testnet.  A 'normal' user has every reason to try things on testnet first while simnet really is for devs or advanced stuff.  And that way the mainnet vs. testnet doc could be very short which would be good.

**Comment by jolan** [comment] 2017-04-15 16:35
This is kind of a dupe of #65 and #78.  We should probably discuss more what we want and decide if the other issues are still relevant and close them if not.

**Comment by jholdstock** [comment] 2017-04-17 12:01
OK well how about changing this issue so it just covers simnet? #65 and #78 don't cover it, and my main motivation for opening this is the fact that simnet is not really covered in the docs at all.

I was thinking just one page in the Advanced section would be adequate.

**Comment by jcvernaleo** [comment] 2017-04-17 12:33
I could live with this being simnet specific and just a page in advanced.

**Closed** 2017-05-02 15:28 UTC
