### ISSUE TITLE
Paymetheus file paths

### ISSUE THREAD

**Issue by raedah** [decred/dcrdocs#343] opened 2017-08-12 16:08 UTC
In the Paymetheus section of the docs, there is no mention of the file paths that Paymetheus uses. Users need this info in order to rename their wallet file in the case where they need to rebuild their wallet from seed if they forgot the passphrase to unlock their wallet.

**Comment by jolan** [comment] 2017-09-13 17:57
Duplicate of #323.

**Closed by jolan** 2017-09-13 17:57 UTC
Labels: duplicate
